### ISSUE TITLE
It return Player doesn't exist when I request friend

### ISSUE THREAD

**Issue by good777LUCKY** [llamadevelopment/FriendSystemNK#4]
I don't know why this error happen. I'm using MySql provider

**Comment by ProxmaDev** [comment]
Please provide more details.

**Comment by good777LUCKY** [comment]
Player is online but this plugin doesn't detect the player even I input nickname correctly

**Comment by good777LUCKY** [comment]
I change config for mysql provider and messages.yml for translation

**Comment by Mundschutziii** [comment]
Do you have pictures or an error? (pictures of user in database and ingame)

**Comment by good777LUCKY** [comment]
No Error log and it says user-not-found

**Comment by ProxmaDev** [comment]
Well, can you make a short video showing the problem?

**Comment by good777LUCKY** [comment]
I can't make video right now.
So
1. I use command /friend
2. Press add friend button
3. Input the player's username
4. press send button
5. it says this message. https://github.com/llama-development/FriendSystemNK/blob/120d31d5aa0690d4b7de6d6576399d84783eb491/src/main/resources/messages.yml#L20

**Comment by ProxmaDev** [comment]
What's the username of the player?

**Comment by good777LUCKY** [comment]
waterpower12435

**Comment by good777LUCKY** [comment]
It was MySQL problem, fixed on https://github.com/llamadevelopment/FriendSystemNK/commit/f46f05fd03c3e6d7c4c46f5685fd30062b4242b7.
